/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AboutModal: typeof import('./src/components/AboutModal.vue')['default']
    AkCheck: typeof import('@kalimahapps/vue-icons/ak')['AkCheck']
    AkXSmall: typeof import('@kalimahapps/vue-icons/ak')['AkXSmall']
    AnOutlinedCopy: typeof import('@kalimahapps/vue-icons/an')['AnOutlinedCopy']
    BxTwitter: typeof import('@kalimahapps/vue-icons/bx')['BxTwitter']
    CgClose: typeof import('@kalimahapps/vue-icons/cg')['CgClose']
    Editor: typeof import('./src/components/Editor.vue')['default']
  }
}
